import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class CountryDataService {
  countryCodes = [
    { code: '+1', name: 'United States' },
    { code: '+44', name: 'United Kingdom' },
    { code: '+91', name: 'India' },
    { code: '+33', name: 'France' },
    { code: '+49', name: 'Germany' },
    { code: '+81', name: 'Japan' },
    { code: '+86', name: 'China' },
    { code: '+7', name: 'Russia' },
    { code: '+61', name: 'Australia' },
    { code: '+971', name: 'United Arab Emirates' },
    { code: '+55', name: 'Brazil' },
    { code: '+351', name: 'Portugal' },
    { code: '+34', name: 'Spain' },
    { code: '+39', name: 'Italy' },
    { code: '+52', name: 'Mexico' },
    { code: '+63', name: 'Philippines' },
    { code: '+90', name: 'Turkey' },
    { code: '+81', name: 'Japan' },
    { code: '+82', name: 'South Korea' },
    { code: '+86', name: 'China' },
    { code: '+81', name: 'Japan' },
    { code: '+971', name: 'United Arab Emirates' },
    { code: '+55', name: 'Brazil' },
    { code: '+20', name: 'Egypt' },
    { code: '+27', name: 'South Africa' },
    { code: '+49', name: 'Germany' },
    { code: '+33', name: 'France' },
    { code: '+91', name: 'India' },
    { code: '+82', name: 'South Korea' },
    { code: '+86', name: 'China' },
    { code: '+7', name: 'Russia' },
    { code: '+81', name: 'Japan' },
    { code: '+44', name: 'United Kingdom' },
    { code: '+234', name: 'Nigeria' },
    { code: '+92', name: 'Pakistan' },
    { code: '+966', name: 'Saudi Arabia' },
    { code: '+61', name: 'Australia' },
    { code: '+506', name: 'Costa Rica' },
    { code: '+354', name: 'Iceland' },
    { code: '+353', name: 'Ireland' },
    { code: '+972', name: 'Israel' },
    { code: '+60', name: 'Malaysia' },
    { code: '+64', name: 'New Zealand' },
    { code: '+31', name: 'Netherlands' },
    { code: '+47', name: 'Norway' },
    { code: '+507', name: 'Panama' },
    { code: '+51', name: 'Peru' },
    { code: '+63', name: 'Philippines' },
    { code: '+48', name: 'Poland' },
    { code: '+351', name: 'Portugal' },
    { code: '+974', name: 'Qatar' },
    { code: '+40', name: 'Romania' },
    { code: '+7', name: 'Russia' },
    { code: '+966', name: 'Saudi Arabia' },
    { code: '+65', name: 'Singapore' },
    { code: '+27', name: 'South Africa' },
    { code: '+34', name: 'Spain' },
    { code: '+94', name: 'Sri Lanka' },
    { code: '+46', name: 'Sweden' },
    { code: '+41', name: 'Switzerland' },
    { code: '+66', name: 'Thailand' },
    { code: '+90', name: 'Turkey' },
    { code: '+380', name: 'Ukraine' },
    { code: '+971', name: 'United Arab Emirates' },
    { code: '+44', name: 'United Kingdom' },
    { code: '+598', name: 'Uruguay' },
    { code: '+58', name: 'Venezuela' },
    { code: '+84', name: 'Vietnam' },
    { code: '+263', name: 'Zimbabwe' },
    { code: '+673', name: 'Brunei' },
    { code: '+975', name: 'Bhutan' },
    { code: '+673', name: 'Brunei' },
    { code: '+509', name: 'Haiti' },
    { code: '+855', name: 'Cambodia' },
    { code: '+856', name: 'Laos' },
    { code: '+960', name: 'Maldives' },
    { code: '+976', name: 'Mongolia' },
    { code: '+977', name: 'Nepal' },
    { code: '+998', name: 'Uzbekistan' },
    { code: '+994', name: 'Azerbaijan' },
    { code: '+994', name: 'Azerbaijan' },
    { code: '+993', name: 'Turkmenistan' },
    { code: '+963', name: 'Syria' },
    { code: '+970', name: 'Palestine' },
    { code: '+967', name: 'Yemen' },
    { code: '+968', name: 'Oman' },
    { code: '+968', name: 'Oman' },
    { code: '+974', name: 'Qatar' },
    { code: '+975', name: 'Bhutan' },
    { code: '+976', name: 'Mongolia' },
    { code: '+977', name: 'Nepal' },
    { code: '+992', name: 'Tajikistan' },
    { code: '+993', name: 'Turkmenistan' },
    { code: '+994', name: 'Azerbaijan' },
    { code: '+995', name: 'Georgia' },
    { code: '+996', name: 'Kyrgyzstan' },
    { code: '+998', name: 'Uzbekistan' },
    { code: '+1-671', name: 'Guam' },
    { code: '+1-684', name: 'American Samoa' },
    { code: '+1-869', name: 'Saint Kitts and Nevis' },
    { code: '+1-758', name: 'Saint Lucia' },
    { code: '+1-767', name: 'Dominica' },
    { code: '+1-784', name: 'Saint Vincent and the Grenadines' },
    { code: '+1-868', name: 'Trinidad and Tobago' },
    { code: '+1-869', name: 'Saint Kitts and Nevis' },
    { code: '+1-876', name: 'Jamaica' },
    { code: '+1-939', name: 'Puerto Rico' },
    { code: '+246', name: 'Diego Garcia' },
    { code: '+297', name: 'Aruba' },
    { code: '+297', name: 'Aruba' },
    { code: '+298', name: 'Faroe Islands' },
    { code: '+299', name: 'Greenland' },
    { code: '+350', name: 'Gibraltar' },
    { code: '+351', name: 'Portugal' },
    { code: '+352', name: 'Luxembourg' },
    { code: '+353', name: 'Ireland' },
    { code: '+354', name: 'Iceland' },
    { code: '+355', name: 'Albania' },
  ];
}
